---
name: mimsy-measurements
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12,<3.13
  - polars>=1.24,<2
  - pyparsing>=3.2,<4
  - python-dotenv>=1.0.1,<2
  - jupytext==1.16.7
  - pip
  - pip:
    - oracledb==3.0.0
    # Optional for pyparsing diagram support
    - jinja2
    - railroad-diagrams
